// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1EM0DPGEkH27FURtA1ZWpoys2tFcusEY',
    appId: '1:925118669171:web:1e26605e52c398b4446506',
    messagingSenderId: '925118669171',
    projectId: 'fixmec-116be',
    authDomain: 'fixmec-116be.firebaseapp.com',
    storageBucket: 'fixmec-116be.firebasestorage.app',
    measurementId: 'G-SWM6XKPM01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ-ALrA3sf-VnQP2ySngo6Azw7gC_dfxE',
    appId: '1:925118669171:android:4e8239e1e00cfc09446506',
    messagingSenderId: '925118669171',
    projectId: 'fixmec-116be',
    storageBucket: 'fixmec-116be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHTup0uZGSPvqqfaxi9CabZeUaM7FEUxs',
    appId: '1:925118669171:ios:18f0ebc7e72dd4d4446506',
    messagingSenderId: '925118669171',
    projectId: 'fixmec-116be',
    storageBucket: 'fixmec-116be.firebasestorage.app',
    iosBundleId: 'com.example.fixmec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHTup0uZGSPvqqfaxi9CabZeUaM7FEUxs',
    appId: '1:925118669171:ios:18f0ebc7e72dd4d4446506',
    messagingSenderId: '925118669171',
    projectId: 'fixmec-116be',
    storageBucket: 'fixmec-116be.firebasestorage.app',
    iosBundleId: 'com.example.fixmec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1EM0DPGEkH27FURtA1ZWpoys2tFcusEY',
    appId: '1:925118669171:web:b3b49cd4bf0f4d97446506',
    messagingSenderId: '925118669171',
    projectId: 'fixmec-116be',
    authDomain: 'fixmec-116be.firebaseapp.com',
    storageBucket: 'fixmec-116be.firebasestorage.app',
    measurementId: 'G-44ZKFC1Z9H',
  );
}
